# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179Cs6fgHSnJkuVx-PxW4sSX3jhMuZV1A
"""

!pip install kagglehub --upgrade pip

import kagglehub

# Download latest version
path = kagglehub.dataset_download("a2015003713/militaryaircraftdetectiondataset")

print("Path to dataset files:", path)

!pip install ultralytics torch torchvision pandas opencv-python split-folders

import os
import zipfile
import shutil
import pandas as pd
import cv2
from ultralytics import YOLO

for root, dirs, files in os.walk(path):
    print("Folder:", root)
    print("Subfolders:", dirs)
    print("Files:", files)
    break

dataset_path = path

os.listdir(dataset_path)

import os

base_path = "/kaggle/input/militaryaircraftdetectiondataset"
dataset_path = os.path.join(base_path, "dataset")
split_csv = os.path.join(base_path, "labels_with_split.csv")

yolo_base = "/kaggle/working/aircraft_yolo"

for s in ["train", "val", "test"]:
    os.makedirs(os.path.join(yolo_base, f"images/{s}"), exist_ok=True)
    os.makedirs(os.path.join(yolo_base, f"labels/{s}"), exist_ok=True)

df_split = pd.read_csv(split_csv)
df_split.head()

df_split['class'].unique()

class_names = df_split['class'].unique()
class_to_id = {name: i for i, name in enumerate(class_names)}
class_to_id

classes = set()

for file in os.listdir(dataset_path):
    if file.endswith(".csv"):
        temp = pd.read_csv(os.path.join(dataset_path, file))
        classes.update(temp['class'].unique())

class_names = sorted(list(classes))
class_to_id = {name: i for i, name in enumerate(class_names)}

print(class_to_id)

for _, row in df_split.iterrows():
    filename = row['filename']
    split = row['split']

    # Map validation → val
    if split == "validation":
        split = "val"

    img_file = filename + ".jpg"
    csv_file = filename + ".csv"

    img_src = os.path.join(dataset_path, img_file)
    csv_src = os.path.join(dataset_path, csv_file)

    if not os.path.exists(img_src) or not os.path.exists(csv_src):
        continue

    # Copy image
    shutil.copy(img_src, os.path.join(yolo_base, "images", split, img_file))

    # Read annotation CSV
    ann = pd.read_csv(csv_src)

    label_path = os.path.join(
        yolo_base,
        "labels",
        split,
        filename + ".txt"
    )

    with open(label_path, "w") as f:
        for _, obj in ann.iterrows():
            img_w = obj['width']
            img_h = obj['height']

            xmin, ymin = obj['xmin'], obj['ymin']
            xmax, ymax = obj['xmax'], obj['ymax']

            # Convert to YOLO format
            x_center = ((xmin + xmax) / 2) / img_w
            y_center = ((ymin + ymax) / 2) / img_h
            box_w = (xmax - xmin) / img_w
            box_h = (ymax - ymin) / img_h

            class_id = class_to_id[obj['class']]

            f.write(f"{class_id} {x_center} {y_center} {box_w} {box_h}\n")

print("Conversion completed successfully")

yaml_content = f"""
path: {yolo_base}
train: images/train
val: images/val

nc: {len(class_names)}
names: {class_names}
"""

with open("/kaggle/working/aircraft.yaml", "w") as f:
    f.write(yaml_content)

# Step 1: Load model (IMPORTANT)
model = YOLO("yolov8m.pt")   # better than yolov8n

# Step 2: Train model
model.train(
    data="/kaggle/working/aircraft.yaml",
    epochs=100,
    imgsz=800,
    batch=16,
    optimizer="AdamW",
    lr0=0.001,
    weight_decay=0.0005,

    # Augmentation
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=10,
    translate=0.1,
    scale=0.5,
    shear=2,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.2,

    patience=20,
    device=0
)